# repos:
# - repo: https://github.com/asottile/pyupgrade
#   rev: v3.21.2
#   hooks:
#     - id: pyupgrade
#       args: [--py310-plus]
#       files: '\.py$'
# - repo: https://github.com/astral-sh/uv-pre-commit
#   rev: 0.9.14
#   hooks:
#     - id: uv-lock
# - repo: https://github.com/astral-sh/ruff-pre-commit
#   # Ruff version.
#   rev: v0.14.7
#   hooks:
#     # Run the linter.
#     - id: ruff
#       types_or: [ python, pyi, jupyter ]
#       args: [ --fix ]
#     # Run the formatter.
#     - id: ruff-format
#       types_or: [ python, pyi, jupyter ]